Add support for wicked2nm in container workflow
In the container workflow no network needs to be configured
because host networking is used. However, for network technology
migrations like wicked to NetworkManager we have to run a
slightly modified setup_host_network service. Compared to the
standard service the container based network service does not
activate the nm connections, because host networking is active
and also stops the NetworkManager in the container instance
to avoid potential conflicts with the network manager tooling
running on the host e.g. wicked

diff --git a/tools/migrate b/tools/migrate
--- a/tools/migrate
+++ b/tools/migrate
@@ -53,6 +53,64 @@ usage() {
     echo "      Run attached to the migration container"
 }
 
+function migration_target {
+    if [[ "${MIGRATION_SYSTEM}" == *containers_sle16* ]]; then
+        echo code16
+    else
+        echo generic
+    fi
+}
+
+function setup_wicked_to_NetworkManager_prereqs {
+    # """
+    # Set up required files for wicked to NetworkManager migration
+    # """
+    if [ -x "$(command -v wicked)" ]; then
+        mkdir -p /var/cache/wicked_config
+        wicked show-config > /var/cache/wicked_config/config.xml
+    fi
+
+    # Create systemd.link file for VMWARE or Hyper-V virtual interfaces
+    for netdev in /sys/class/net/*; do
+        dev=$(basename "${netdev}")
+        link_file=/etc/systemd/network/70-persistent-net-"${dev}".link
+        test -e "${link_file}" && continue
+
+        ! grep -E '^(00:0c:29:|00:50:56:|00:15:5d:)' \
+            /sys/class/net/"${dev}"/address >/dev/null && continue
+        ID_PATH=$(
+            udevadm info -q property --property=ID_PATH \
+            /sys/class/net/"${dev}"
+        )
+        ID_PATH=${ID_PATH#ID_PATH=}
+        ID_NET_DRIVER=$(
+            udevadm info -q property --property=ID_NET_DRIVER \
+            /sys/class/net/"${dev}"
+        )
+        ID_NET_DRIVER=${ID_NET_DRIVER#ID_NET_DRIVER=}
+        if [ -z "$ID_PATH" ] || [ -z "$ID_NET_DRIVER" ]; then
+            echo "[ERROR] failed to create systemd.link file for ${dev}"
+            exit 1
+        fi
+        grep -sE '^Name="?'"$dev"'"?$' \
+            /etc/systemd/network/*.link && continue
+        grep -sE '^\s*[^#].*[ \t,]NAME="'"$dev"'"$' \
+            /etc/udev/rules.d/*.rules && continue
+
+        echo "Create $link_file with Path=$ID_PATH Driver=$ID_NET_DRIVER"
+        cat > "${link_file}" <<-EOT
+		# This file was created from run_migration
+		[Match]
+		Path=$ID_PATH
+		Driver=$ID_NET_DRIVER
+		[Link]
+		NamePolicy=
+		Name=$dev
+		EOT
+    done
+}
+
+
 migrate() {
     set -x
     local detach="--detach"
@@ -162,7 +220,13 @@ if [ "${argZypperDup}" ];then
     echo "use_zypper_migration: false" >> /etc/sle-migration-service.yml
 fi
 
+if [ "$(migration_target)" = "code16" ]; then
+    setup_wicked_to_NetworkManager_prereqs
+fi
+
 migrate
+
+dracut -f
 
 if [ "${argReboot}" ];then
     sudo reboot -f
