Create systemd.link files for virtual VMware/Hyper-V NICs
The 75-persistent-net-generator.rules does not create udev-rules
for virtual nics, matching the hwaddr "00:0c:29:*|00:50:56:*" (VMware)
or "00:15:5d:*" (Hyper-V).
When migrating to SLE16, predictable ifnames are enabled and it
is very likely, that the nic will get a different name.

To fix this, create 'systemd.link' files matching the DRIVER and
PCI_ID to ensure the virtual NIC retains its  expected name.
(bsc#1250076)

diff --git a/tools/run_migration b/tools/run_migration
--- a/tools/run_migration
+++ b/tools/run_migration
@@ -117,6 +117,37 @@ function setup_wicked_to_NetworkManager_prereqs {
         mkdir -p /var/cache/udev_rules
         sed -e 's/KERNEL=="eth\*"/KERNEL=="e\*"/g' -e 's/KERNEL=="wlan\*"/KERNEL=="w\*"/g' /etc/udev/rules.d/70-persistent-net.rules > /var/cache/udev_rules/70-migration-persistent-net.rules
     fi
+
+    # Create systemd.link file for VMWARE or Hyper-V virtual interfaces
+    for dev in $(ls -1 /sys/class/net); do
+        link_file=/etc/systemd/network/70-persistent-net-$dev.link
+        test -e $link_file && continue
+
+        ! grep -E '^(00:0c:29:|00:50:56:|00:15:5d:)' /sys/class/net/$dev/address >/dev/null && continue
+        ID_PATH=$(udevadm info -q property --property=ID_PATH /sys/class/net/$dev)
+        ID_PATH=${ID_PATH#ID_PATH=}
+        ID_NET_DRIVER=$(udevadm info -q property --property=ID_NET_DRIVER /sys/class/net/$dev)
+        ID_NET_DRIVER=${ID_NET_DRIVER#ID_NET_DRIVER=}
+        if [ -z "$ID_PATH" ] || [ -z "$ID_NET_DRIVER" ]; then
+            echo "[ERROR] failed to create systemd.link file for $dev"
+            exit 1
+        fi
+        grep -sE '^Name="?'"$dev"'"?$' /etc/systemd/network/*.link && continue
+        grep -sE '^\s*[^#].*[ \t,]NAME="'"$dev"'"$' /etc/udev/rules.d/*.rules && continue
+
+        echo "Create $link_file with Path=$ID_PATH Driver=$ID_NET_DRIVER"
+        cat > $link_file <<EOT
+# This file was created from run_migration
+[Match]
+Path=$ID_PATH
+Driver=$ID_NET_DRIVER
+
+[Link]
+NamePolicy=
+Name=$dev
+EOT
+
+    done
 }
 
 function store_snapper_pre_snapshot {
