shellcheck heavily complained
Fix shell coding in run_migration and %post scripts
to match with standards reported by shellcheck

diff --git a/package/suse-migration-sle16-activation-spec-template b/package/suse-migration-sle16-activation-spec-template
--- a/package/suse-migration-sle16-activation-spec-template
+++ b/package/suse-migration-sle16-activation-spec-template
@@ -49,46 +49,56 @@ install -D -m 755 grub.d/99_migration \
 # SLE16 image panics on CPUs older than x86_64_v2 (i.e. x86_64) (bsc#1249593), so we need to block migration before getting into the image.
 # We need the ZYPP_READONLY_HACK here since we are running inside a zypper transaction; without this the invocation of zypper will fail due to locking issues.
 if [ "$(ZYPP_READONLY_HACK=1 zypper system-architecture)" == "x86_64" ]; then
-   echo "CPU Architecture too old. Aborting installation."
-   exit 1
+    echo "CPU Architecture too old. Aborting installation."
+    exit 1
 fi
 
 # store snapper pre snapshot if available
 if [ -x /usr/bin/snapper ]; then
-  PRE_SNAPSHOT=$(snapper -c root --machine-readable csv list --disable-used-space --columns subvolume,number,type 2>/dev/null| grep '^/,[^,]*,pre' |sed -e '$!d' -e 's|/,\([^,]*\),pre|\1|g')
-  if [ "x$PRE_SNAPSHOT" != x ]; then
-     echo $PRE_SNAPSHOT > /var/cache/suse_migration_snapper_btrfs_pre_snapshot_number
-  fi
+    PRE_SNAPSHOT=$(snapper -c root --machine-readable csv list --disable-used-space --columns subvolume,number,type 2>/dev/null| grep '^/,[^,]*,pre' |sed -e '$!d' -e 's|/,\([^,]*\),pre|\1|g')
+    if [ "x$PRE_SNAPSHOT" != x ]; then
+        echo $PRE_SNAPSHOT > /var/cache/suse_migration_snapper_btrfs_pre_snapshot_number
+    fi
 fi
 # Setup wicked to NetworkManager migration files
 if [ -x "$(command -v wicked)" ]; then
-  mkdir -p /var/cache/wicked_config
-  wicked show-config > /var/cache/wicked_config/config.xml
+    mkdir -p /var/cache/wicked_config
+    wicked show-config > /var/cache/wicked_config/config.xml
 fi
 if [ -f /etc/udev/rules.d/70-persistent-net.rules ]; then
-  mkdir -p /var/cache/udev_rules
-  sed -e 's/KERNEL=="eth\*"/KERNEL=="e\*"/g' -e 's/KERNEL=="wlan\*"/KERNEL=="w\*"/g' /etc/udev/rules.d/70-persistent-net.rules > /var/cache/udev_rules/70-migration-persistent-net.rules
+    mkdir -p /var/cache/udev_rules
+    sed -e 's/KERNEL=="eth\*"/KERNEL=="e\*"/g' -e 's/KERNEL=="wlan\*"/KERNEL=="w\*"/g' /etc/udev/rules.d/70-persistent-net.rules > /var/cache/udev_rules/70-migration-persistent-net.rules
 fi
 
 # Create systemd.link file for VMWARE or Hyper-V virtual interfaces
-for dev in $(ls -1 /sys/class/net); do
-  link_file=/etc/systemd/network/70-persistent-net-$dev.link
-  test -e $link_file && continue
+for netdev in /sys/class/net/*; do
+    dev=$(basename "$netdev")
+    link_file=/etc/systemd/network/70-persistent-net-"$dev".link
+    test -e "$link_file" && continue
 
-  ! grep -E '^(00:0c:29:|00:50:56:|00:15:5d:)' /sys/class/net/$dev/address >/dev/null && continue
-  ID_PATH=$(udevadm info -q property --property=ID_PATH /sys/class/net/$dev)
-  ID_PATH=${ID_PATH#ID_PATH=}
-  ID_NET_DRIVER=$(udevadm info -q property --property=ID_NET_DRIVER /sys/class/net/$dev)
-  ID_NET_DRIVER=${ID_NET_DRIVER#ID_NET_DRIVER=}
-  if [ -z "$ID_PATH" ] || [ -z "$ID_NET_DRIVER" ]; then
-    echo "[ERROR] failed to create systemd.link file for $dev"
-    exit 1
-  fi
-  grep -sE '^Name="?'"$dev"'"?$' /etc/systemd/network/*.link && continue
-  grep -sE '^\s*[^#].*[ \t,]NAME="'"$dev"'"$' /etc/udev/rules.d/*.rules && continue
+    ! grep -E '^(00:0c:29:|00:50:56:|00:15:5d:)' \
+        /sys/class/net/"$dev"/address >/dev/null && continue
+    ID_PATH=$(
+        udevadm info -q property --property=ID_PATH \
+        /sys/class/net/"$dev"
+    )
+    ID_PATH=${ID_PATH#ID_PATH=}
+    ID_NET_DRIVER=$(
+        udevadm info -q property --property=ID_NET_DRIVER \
+        /sys/class/net/"$dev"
+    )
+    ID_NET_DRIVER=${ID_NET_DRIVER#ID_NET_DRIVER=}
+    if [ -z "$ID_PATH" ] || [ -z "$ID_NET_DRIVER" ]; then
+        echo "[ERROR] failed to create systemd.link file for $dev"
+        exit 1
+    fi
+    grep -sE '^Name="?'"$dev"'"?$' \
+        /etc/systemd/network/*.link && continue
+    grep -sE '^\s*[^#].*[ \t,]NAME="'"$dev"'"$' \
+        /etc/udev/rules.d/*.rules && continue
 
-  echo "Create $link_file with Path=$ID_PATH Driver=$ID_NET_DRIVER"
-  cat > $link_file <<EOT
+    echo "Create $link_file with Path=$ID_PATH Driver=$ID_NET_DRIVER"
+    cat > "$link_file" <<EOT
 # This file was created from suse-migration-sle16-activation
 [Match]
 Path=$ID_PATH
